name: Linter
on: 
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Linter
    steps:
    - name: Setup action
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8-eradicate  
        python -m pip install radon
        python -m pip install dlint
 
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18.6
      with:
        files: |
          **/*.py

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - name: Analyze the code with Flake8 and Radon
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          python -m flake8 --radon-max-cc 6 --max-line-length n "$file"
        done
    - name: Analyze the code with Dlint
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          python -m flake8 --print-dlint-linters "$file"
        done
