name: Integration tests
on: 
  workflow_call:
    secrets:
      organization_key:
        required: true
jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
    - name: Setup action
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Load private keys to pipeline
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: |
          ${{ secrets.organization_key }}

    - name: Cache dependencies to speed up the workflow
      uses: actions/cache@v1
      id:   cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_tests.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone git@github.com:Kongsberg-Predictive-Maintenance/thruster-digital-twin.git
        pip install -r thruster-digital-twin/requirements.txt
        pip install -r ../thruster-digital-twin/integration_tests/requirements_integration_tests.txt
        pip install .

    - name: Test with pytest
      run: |
        python -m pytest thruster-digital-twin/integration_tests
