name: Linter
on: 
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Linter
    steps:

    - name: Cached LFS checkout
      uses: nschloe/action-cached-lfs-checkout@v1.1.2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -v -m pip install --upgrade pip
        python -v -m pip install "pylint==2.13.5"
 
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18.6
      with:
        files: |
          **/*.py
        files_ignore: |
          doc/**
          badges/**

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - name: Analyze the code with linter
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          python -m pylint "$file" --rcfile ".pylintrc"
        done
