name: Tests
on: 
  workflow_call:
    secrets:
      organization_key:
        required: true
jobs:
  build:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Setup action
      uses: nschloe/action-cached-lfs-checkout@v1
      with:
        exclude: "docs/*"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        cache: 'pip' # caching pip dependencies

    - name: Load private keys to pipeline
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: |
          ${{ secrets.organization_key }}

    - name: Cache dependencies to speed up the workflow
      uses: actions/cache@v1
      id:   cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_tests.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -v -r tests/requirements_tests.txt

    - name: Test with pytest
      run: |
        python -m pytest tests
